name: promotion_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider_plus: ^7.1.0
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  expandable_page_view: ^1.0.17
  file_picker: ^8.1.7
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  syncfusion_flutter_datagrid: ^27.1.55
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/pictures/
    - assets/images/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

flutter_assets:
  assets_path:
    - assets/images/
  output_path: lib/core/constants
  filename: assets.dart
  field_prefix: null
  ignore_comments: true
